{{ if .Values.tls }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: company-secrets
  namespace: {{ .Values.backend.namespace }}
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.keyvault.name }}
    tenantId: {{ .Values.keyvault.tenant_id }}
    objects: |
      array:
        - |
          objectName: company-certificate
          objectType: secret

{{ end }}
