{{ if .Values.tls }}

apiVersion: v1
kind: Secret
metadata:
  name: keyvault-credentials
  namespace: {{ .Values.client.namespace }}
  labels:
    secrets-store.csi.k8s.io/used: "true"
type: Opaque
stringData:
  clientid: {{ .Values.keyvault.credentials.id }}
  clientsecret: {{ .Values.keyvault.credentials.secret }}

{{ end }}
